---
- hosts: all
  tasks:
    - name: Adding APT repository key
    when: ansible_os_family == 'Debian'
    sudo: yes
    apt_key:
      url: "http://nginx.org/keys/nginx_signing.key"
    tags:
      - nginx
      - frontend
      - repo
    - name : Define hostname
      shell: hostnamectl set-hostname jumper.rfs.local
      become: yes
    - name: Install Dependencies
      ansible.builtin.apt:
        pkg:
        - ssh
        - libreswan
    - name: Install nginx
      apt: name=nginx state=latest
    - name: start nginx
      shell: systemctl start nginx