---
#
# NginX redirector Debian 12 by RFS
#

- hosts: "*"
  remote_user: debian
  become_method: sudo
  tasks:
    - name : Define hostname
      shell: hostnamectl set-hostname dev.rfs.local
      become: yes

    - name: Install Dependencies
      ansible.builtin.apt:
        pkg:
        - ssh
        - libreswan
        - nginx
      become: yes