---
#
# NginX redirector Debian 12 by RFS
#

- hosts: "*"
  remote_user: debian
  become_method: sudo
  tasks:
    - include_role: name=ansible-libreswan
    - name: Set a hostname
      ansible.builtin.hostname:
        name: web01
        use: systemd

    - name: Install Dependencies
      ansible.builtin.apt:
        pkg:
        - ssh
        - libreswan
        - nginx
      become: yes