---
#
# NginX redirector Debian 12 by RFS
#

- hosts: "*"
  remote_user: debian
  become_method: sudo
  tasks:
    - name : Define hostname
      shell: hostnamectl set-hostname dev.rfs.local
      become: yes
      
    - name: Adding APT repository key
      when: ansible_os_family == 'Debian'
      sudo: yes
      apt_key:
        url: "http://nginx.org/keys/nginx_signing.key"

    - name: Install Dependencies
      ansible.builtin.apt:
        pkg:
        - ssh
        - libreswan
        - nginx

    - name: start nginx
      shell: systemctl start nginx